### ISSUE TITLE
Is there a way to run this on windows?

### ISSUE THREAD

**Issue by iChristGit** [darabos/ai-alchemy#1]
The last part is giving me error on Windows 11, is there a way to run it? i have comfy installed

**Comment by darabos** [comment]
I've only tried it on Linux, but if Comfy can run on your system then I think we can get this to run too. What error did you get?

**Comment by iChristGit** [comment]
> I've only tried it on Linux, but if Comfy can run on your system then I think we can get this to run too. What error did you get?

Thank you for the help!
I installed all pip requirments, and I get this for the run.sh file:
C:\Users\User\Downloads\ai-alchemy-main>CONFIG=elemental.yml ./run.sh
'CONFIG' is not recognized as an internal or external command,
operable program or batch file.

**Comment by darabos** [comment]
> 'CONFIG' is not recognized as an internal or external command,

Ah, right. How do you set environment variables in Windows... Maybe something like this?

```
set CONFIG=elemental.yml
curl "https://unpkg.com/vue@3.3.10/dist/vue.esm-browser.js" > vue.js
uvicorn server:app --reload --host 0
```

**Comment by iChristGit** [comment]
> uvicorn server:app --reload --host 0

I did all the commands (CMD)
I get this error:
INFO:     Will watch for changes in these directories: ['C:\\Users\\User\\Downloads\\ai-alchemy-main']
ERROR:    [Errno 11001] getaddrinfo failed

I made sure ComfyUI is working on  a different CMD window.

**Comment by darabos** [comment]
That might be related to the `--host 0` flag. Try without?

I can try this on Windows myself later tonight. For all I know these could be the first few errors out of 100. 😅

**Comment by iChristGit** [comment]
> That might be related to the `--host 0` flag. Try without?
> 
> I can try this on Windows myself later tonight. For all I know these could be the first few errors out of 100. 😅

Now it works! without --host 0
It downloads models and tokenizers, and it says  Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
Il wait for download to finish and ill check the URL

**Comment by iChristGit** [comment]
![image](https://github.com/darabos/ai-alchemy/assets/20077386/57106b86-5e8b-4d87-9dec-a009e5b44c0a)

Its working!
So, the needed commands on windows, after running comfyui:

```
pip install -r requierments.txt
set CONFIG=elemental.yml
curl "https://unpkg.com/vue@3.3.10/dist/vue.esm-browser.js" > vue.js
uvicorn server:app --reload 
``` 
You can add it to readme maybe? after you confirm it works also in your windows install. (I have Win11, so maybe you should check on W10/W7)

**Comment by iChristGit** [comment]
Also, how can i change to a different style? like the animals one you shown in the images?

**Comment by darabos** [comment]
Fantastic! I will add it to the readme!

> Also, how can i change to a different style? like the animals one you shown in the images?

Instead of `set CONFIG=elemental.yml` change it to some other yml file in the `configs` directory. Make your own config!

**Comment by iChristGit** [comment]
> Fantastic! I will add it to the readme!
> 
> > Also, how can i change to a different style? like the animals one you shown in the images?
> 
> Instead of `set CONFIG=elemental.yml` change it to some other yml file in the `configs` directory. Make your own config!

Amazing! thank you for this project, will introduce it to my son, im sure he will be hooked!

**Comment by darabos** [comment]
I changed the code so you can choose the config on the UI instead of setting `CONFIG`. (3cc75afd8bcdeb0b73c705cf8fb5f0ec7ef9b20f) This way I don't have to make the readme more complex. 😅 Thanks!
